/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package earth.levi.dropbox.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param path 
 * @param recursive 
 * @param includeMediaInfo 
 * @param includeDeleted 
 * @param includeHasExplicitSharedMembers 
 * @param includeMountedFolders 
 * @param includeNonDownloadableFiles 
 */
@Serializable

data class ListFolderRequestModel (

    @SerialName(value = "path") val path: kotlin.String? = null,

    @SerialName(value = "recursive") val recursive: kotlin.Boolean? = null,

    @SerialName(value = "include_media_info") val includeMediaInfo: kotlin.Boolean? = null,

    @SerialName(value = "include_deleted") val includeDeleted: kotlin.Boolean? = null,

    @SerialName(value = "include_has_explicit_shared_members") val includeHasExplicitSharedMembers: kotlin.Boolean? = null,

    @SerialName(value = "include_mounted_folders") val includeMountedFolders: kotlin.Boolean? = null,

    @SerialName(value = "include_non_downloadable_files") val includeNonDownloadableFiles: kotlin.Boolean? = null

)

