name: Deploy snapshot builds

on: [push]

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  files-changed:
    name: Detect what files changed to only make snapshot if source code gets edited 
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      src: ${{ steps.changes.outputs.src }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'src/**'              

  publish-snapshot:
    needs: files-changed
    if: needs.files-changed.outputs.src == 'true' 
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 16
          cache: 'gradle'

      - name: Get branch names to use later 
        id: branch-name
        uses: tj-actions/branch-names@v6

      - run: ./gradlew publishModulePublicationToMavenRepository
        env:
          GRADLE_PUBLISH_USERNAME: levibostian
          GRADLE_PUBLISH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}          
          LIBRARY_VERSION: "${{ steps.branch-name.outputs.current-branch }}-SNAPSHOT"

  cleanup-old-snapshots:
    needs: files-changed
    if: needs.files-changed.outputs.src == 'true' 
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete old packages to reduce carbon footprint of project
        uses: actions/delete-package-versions@v3
        with:
          package-name: 'earth.levi.dropbox'
          min-versions-to-keep: 10

