name: Tests 

on: [push]

jobs:
  build-project:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1      
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version-file: .java-version
      - name: Setup Gradle and enable caching 
        uses: gradle/gradle-build-action@v2
        
      - name: Compile the source code 
        run: ./gradlew build
