# Inspired from: https://github.com/peter-evans/gradle-auto-dependency-updates
name: Update dependencies

on:
  schedule:
    - cron:  '0 1 * * 1' # https://crontab.guru/#0_1_*_*_1  

jobs:
  update-gradle-dependencies:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # required to make PR
      contents: write # required to make PR
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1      
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version-file: .java-version
      - name: Setup Gradle and enable caching 
        uses: gradle/gradle-build-action@v2

      - name: Perform dependency resolution and write new lockfiles
        run: ./gradlew dependencies --write-locks

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "build: update gradle dependencies"
          branch: bot/update-gradle-dependencies